### ISSUE TITLE
great. ENglish translation???

### ISSUE THREAD

**Issue by ksdavidc** [open-scratch/teaching-open#10]
This is very cool. Any chance of an English translation???

**Comment by chengyu2333** [comment]
I am very sorry that the system is mainly provided to Chinese educational institutions at present. The international version has not been developed yet. You can use translation software to modify the code and sql data, and the workload is not too much (*^_^*).

**Comment by chengyu2333** [comment]
By the way. The cloud object store is based on https:///qiniu.com. You can modify the source code to use AWS S3, or sign up for qiniu.com.
If you have any questions.You can submit an issue here.We can offer help and solutions.

**Comment by ksdavidc** [comment]
Thank you so much for your kind replies. I am very interested in trying it
out, because I am teaching scratchjr and scratch (an other things) now and
I can see this would be very useful, though only a few small classes at
this point. I have to present it to my team and see if we are up for the
challenge. We are a very small group with limited resources.

It is kind that you offer support. I worry that I will have so many
questions that I would likely become very annoying. I am seeking some help
among my colleagues here so that I can be better informed in asking the
right questions if I need to.

At this stage, I am trying to figure out the big picture to see if it is
even within our capabilities. For example, the tutorial mentions
"SpringBoot_2.1.3.RELEASE
+ Mybatis-plus_3.1.2 + Shiro_1.4.0..." + a long list of other technologies,
but it seems that to get up and running you just really need mysql5.6, redis
6.0,  Java, and  Nginx. Is that right? Of course, translating it on top of
that! It  appears it might be straightforward for someone with the right
experience, but my experience is not sufficient in all these areas to do it
myself. If you have any suggestions on how I can get a better handle on
what the steps are that would help.

I don't know know what kind of server we would set up, but your are right
something like AWS S3 is probably easier than qiniu for us. If we move
ahead I may certainly have questions about that.

All that said, I do thank you once again and I hope I can make this work....

**Comment by chengyu2333** [comment]
If you just need to use the system and don't need to redevelop it.Then you don't need to worry about the technical framework and implementation.If you really feel difficult, we can help you directly deploy to the server.Just need to do is prepare the server and the domain name (or sub domain name).If you need more efficient help, you can add me as WeChat or Telegram friend.
