### ISSUE TITLE
使用Python编辑器执行错误

### ISSUE THREAD

**Issue by reasonpun** [open-scratch/teaching-open#12]
```python

a = 10

for j in range(a):

    b = a-j

    print(" " * b,end="")

    c = 2*j+1

    print("*"*c)

```

SyntaxError: bad input on line 4

执行如上代码提示 bad input。

```python

print(" " * b,end="")
```
SyntaxError: bad input on line 1

貌似使用print()方法，并添加第二个end参数(或者sep参数)都会出现这个问题。
请问大佬这是怎么回事呢？
谢谢~

**Comment by chengyu2333** [comment]
图形化python使用的并不是真实的python环境，而是js模拟的。有些命令和真正的python还是有区别的。

**Comment by reasonpun** [comment]
> 图形化python使用的并不是真实的python环境，而是js模拟的。有些命令和真正的python还是有区别的。

好的，谢谢
