### ISSUE TITLE
前端打包部署到服务器上，不显示验证码

### ISSUE THREAD

**Issue by gyz147** [open-scratch/teaching-open#8]
nginx也指向build目录了。后台启动也正确。
F12 network里查看时请求验证码那条网络请求没请求成功。
本来时这样的http://服务器IP/api/sys/randomImage/1603807496161?_t=1603807496，请求不成功。
我改成http://服务器IP:8080/api/sys/randomImage/1603807496161?_t=1603807496打到浏览器上，就能请求成功。
是不是代理什么的原因?

**Comment by chengyu2333** [comment]
api反向代理一下
